### ISSUE TITLE
Improve the login page

### ISSUE THREAD

**Issue by Trailblazerr1** [Trailblazerr1/FaceMe-test#4]
Currently the login page looks something like [this](https://github.com/Trailblazerr1/FaceMe/blob/master/Screenshot%20from%202017-01-17%2017-20-12.png).
Create a new login page from scratch with all the links as shown in above image.

**Comment by Heerendarji** [comment]
I would like to get started on this.

**Comment by gauthamzz** [comment]
could you come on gitter and talk to the mentors before adding the label opencode. We would like to dicuss somethings :smile: 

Cheers,

Team OpenCode
